# Generated by Django 3.1.5 on 2021-02-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung der Datei', max_length=1000, verbose_name='Titel')),
                ('file', models.FileField(help_text='Datei hochladen.', upload_to='material/', verbose_name='Datei')),
                ('category', models.CharField(help_text='Kategorie der Datei', max_length=100, verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materialien',
            },
        ),
    ]
