# Generated by Django 3.1.5 on 2021-03-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Materialien', 'verbose_name_plural': 'Materialien'},
        ),
    ]
