# Generated by Django 3.1.5 on 2021-03-04 17:22

from django.db import migrations, models
import materials_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Materialien', 'verbose_name_plural': 'Materialien'},
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(help_text='Datei hochladen.', upload_to='material/', validators=[materials_page.models.validate_pdf_extension], verbose_name='Datei'),
        ),
    ]
