# Generated by Django 3.1.14 on 2022-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials_page', '0003_auto_20210312_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(help_text='Bezeichnung der Datei', max_length=100, verbose_name='Titel'),
        ),
    ]
