# Generated by Django 3.1.5 on 2021-01-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicdate',
            name='date_ca',
            field=models.BooleanField(default=False, help_text='ca. zum Datum hinzufügen (für ungenaue Datumsangaben).'),
        ),
        migrations.AddField(
            model_name='historicdate',
            name='date_century',
            field=models.BooleanField(default=False, help_text='Sind die Daten Jahrhundert Angaben?'),
        ),
    ]
