# Generated by Django 3.1.5 on 2021-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20210126_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicdate',
            name='exacter_date',
            field=models.DateField(blank=True, help_text="Falls das Ereignis ein genaueres Datum hat,\n                                    hier eingeben.\n                                    Diese Feld unterstützt zusätzlich zur Jahreszahl \n                                    wie obendrüber), \n                                    Monats- und Tagesangaben, es kann aber auch leer bleiben.\n                                    Falls diese und die Jahreszahl gesetzt sind, \n                                    wird dieses genauere Datum das \n                                    sein, dass angezeigt wird. \n                                    ACHTUNG: Jahreszahlen bitte vierstellig eingeben: \n                                    Das Jahr '17' wird sonst automatisch zu '2017' erweitert, \n                                    möchte man das Jahr 17 haben, muss man '0017' eingeben.", null=True),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='infos',
            field=models.TextField(editable=False, help_text='Hier eine kurze Beschreibung des historischen Ereignisses einfügen (max. 1000 Zeichen).', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='year',
            field=models.PositiveIntegerField(default=0, help_text='Hier das Jahr des Ereignisses einfügen.\n                                        Falls es ein genaueres Datum gibt, wird diese angezeigt.'),
        ),
    ]
