# Generated by Django 3.1.5 on 2021-02-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0005_auto_20210216_1433'),
        ('timeline', '0003_auto_20210129_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicdate',
            options={'verbose_name': 'Historisches Datum', 'verbose_name_plural': 'Historische Daten'},
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='date_ca',
            field=models.BooleanField(default=False, help_text='ca. zum Datum hinzufügen (für ungenaue Datumsangaben).', verbose_name='ungefähres Datum?'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='date_century',
            field=models.BooleanField(default=False, help_text='Sind die Daten Jahrhundert Angaben?', verbose_name='Jahrhundert'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='era',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.era', verbose_name='Epoche'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='exacter_date',
            field=models.DateField(blank=True, help_text="Falls das Ereignis ein genaueres Datum hat, hier eingeben. Diese Feld unterstützt zusätzlich zur Jahreszahl (wie obendrüber), Monats- und Tagesangaben, es kann aber auch leer bleiben. Falls diese und die Jahreszahl gesetzt sind, wird dieses genauere Datum das sein, dass angezeigt wird. ACHTUNG: Jahreszahlen bitte vierstellig eingeben: Das Jahr '17' wird sonst automatisch zu '2017' erweitert, möchte man das Jahr 17 haben, muss man '0017' eingeben.", null=True, verbose_name='Exaktes Datum'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='infos',
            field=models.TextField(editable=False, help_text='Hier eine kurze Beschreibung des historischen Ereignisses einfügen (max. 1000 Zeichen).', max_length=1000, verbose_name='Information'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='title',
            field=models.CharField(help_text='Hier einen Titel für der Ereignis einfügen (max. 100 Zeichen).', max_length=100, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='year',
            field=models.PositiveIntegerField(default=0, help_text='Hier das Jahr des Ereignisses einfügen. Falls es ein genaueres Datum gibt, wird diese angezeigt.', verbose_name='Jahr'),
        ),
        migrations.AlterField(
            model_name='historicdate',
            name='year_BC_or_AD',
            field=models.CharField(choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Ereignisses: v.Chr. bzw. n.Chr. auswählen.', max_length=7, verbose_name='vor oder nach Christigeburt?'),
        ),
    ]
