# Generated by Django 3.1.14 on 2021-12-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.CharField(editable=False, max_length=500, verbose_name='URL')),
                ('name', models.CharField(editable=False, max_length=100, verbose_name='Bezeichnung')),
                ('month', models.PositiveIntegerField(default=0, editable=False, verbose_name='Für Monat')),
                ('year', models.PositiveIntegerField(default=0, editable=False, verbose_name='Für Jahr')),
                ('visits', models.PositiveIntegerField(default=0, editable=False, verbose_name='Anzahl der Besuche')),
            ],
            options={
                'verbose_name': 'Erhebung',
                'verbose_name_plural': 'Erhebungen',
            },
        ),
    ]
