# Generated by Django 3.1.14 on 2022-02-02 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={},
        ),
    ]
