# Generated by Django 3.1.5 on 2021-11-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='introtexts',
            options={'verbose_name': 'Intro-Seiten Texte', 'verbose_name_plural': 'Intro-Seiten Texte'},
        ),
    ]
