# Generated by Django 3.1.14 on 2022-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0002_auto_20211109_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introtexts',
            name='buildings_card_text',
            field=models.TextField(help_text='Text für die Bauwerke Karte (max. 200 Zeichen).', max_length=250, verbose_name='Bauwerke Karten Text'),
        ),
        migrations.AlterField(
            model_name='introtexts',
            name='timeline_card_text',
            field=models.TextField(help_text='Text für die Zeitachsen Karte (max. 200 Zeichen).', max_length=250, verbose_name='Zeitachsen Karten Text'),
        ),
        migrations.AlterField(
            model_name='introtexts',
            name='video_card_text',
            field=models.TextField(help_text='Text für die Video Karte (max. 200 Zeichen).', max_length=250, verbose_name='Video Karten Text'),
        ),
    ]
