# Generated by Django 3.1.5 on 2021-01-19 15:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('details_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titel des Videos', max_length=100)),
                ('video', models.FileField(help_text='Videodatei in .mp4', upload_to='videos/')),
                ('intro', models.BooleanField(default=False, help_text='Ist dieses Video das Intro-Video?')),
                ('length', models.FloatField(help_text='Länge des Videos', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('era', models.ForeignKey(help_text='Epoche des Videos auswählen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details_page.era')),
                ('era2', models.ForeignKey(blank=True, help_text='Falls das Video in zwei Epochen fällt, kann hier eine zweite\n                             hinzugefügt werden. Diese Feld kann auch leer bleiben.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details_page.era')),
            ],
        ),
        migrations.CreateModel(
            name='Timestamps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(help_text='Zugehöriges Gebäude', null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.building')),
                ('video', models.ForeignKey(help_text='Zugehöriges Video', on_delete=django.db.models.deletion.CASCADE, to='video_content.video')),
            ],
        ),
    ]
