# Generated by Django 3.1.5 on 2021-01-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video', models.FileField(upload_to='videos/')),
                ('era', models.CharField(choices=[('Frühzeit', 'Frühzeit'), ('Archaik', 'Archaik'), ('Klassik', 'Klassik'), ('Hellenismus', 'Hellenismus'), ('Römische Kaiserzeit', 'Römische Kaiserzeit'), ('Spätantike', 'Spätantike'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', max_length=100)),
                ('intro', models.BooleanField(default=False)),
            ],
        ),
    ]
