# Generated by Django 3.1.4 on 2021-01-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='era',
            field=models.CharField(default='', max_length=100),
        ),
    ]
