# Generated by Django 3.1.5 on 2021-01-28 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0001_initial'),
        ('video_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=0, height_field='height', help_text='Hier das Vorschaubild zum Video hochladen.', upload_to='pics/thumbnails/', width_field='width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='time',
            field=models.FloatField(help_text='Geben Sie hier eine Stelle ein, an dem das gewählte Gebäude im Video erscheint', validators=[django.core.validators.MinValueValidator(0.0, 'Keine Werte kleiner als Null')]),
        ),
        migrations.AlterField(
            model_name='video',
            name='era2',
            field=models.ForeignKey(blank=True, help_text='Falls das Video in zwei Epochen fällt, \n                             kann hier eine zweite\n                             hinzugefügt werden. Diese Feld kann auch leer bleiben.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details_page.era'),
        ),
    ]
