# Generated by Django 3.1.5 on 2021-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content', '0002_auto_20210128_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=None, height_field='height', help_text='Hier das Vorschaubild zum Video hochladen.', null=True, upload_to='pics/thumbnails/', width_field='width'),
        ),
    ]
