# Generated by Django 3.1.5 on 2021-01-29 09:06
import django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('details_page', '0003_auto_20210129_1734'),
        ('video_content', '0002_auto_20210128_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=None, height_field='height',
                                    help_text='Hier das Vorschaubild zum Video hochladen.',
                                    null=True, upload_to='pics/thumbnails/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='video',
            name='era2',
            field=models.ForeignKey(blank=True,
                                    help_text='Falls das Video in zwei Epochen fällt,\n'
                                              'kann hier eine zweite\n'
                                              'hinzugefügt werden. Diese Feld kann auch leer bleiben.',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='details_page.era'),
        ),
    ]
