# Generated by Django 3.1.5 on 2021-02-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0004_auto_20210203_2023'),
        ('video_content', '0003_auto_20210129_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='era2',
            field=models.ForeignKey(blank=True, help_text='Falls das Video in zwei Epochen fällt,\n                             kann hier eine zweite\n                             hinzugefügt werden. Diese Feld kann auch leer bleiben.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details_page.era'),
        ),
    ]
