# Generated by Django 3.1.5 on 2021-02-16 13:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0005_auto_20210216_1433'),
        ('video_content', '0004_auto_20210203_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timestamp',
            options={'verbose_name': 'Timestamp', 'verbose_name_plural': 'Timestamps'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.RemoveField(
            model_name='timestamp',
            name='time',
        ),
        migrations.AddField(
            model_name='timestamp',
            name='minutes',
            field=models.PositiveIntegerField(default=1, help_text='Geben Sie hier die Minuten an, an dem das gewählte Gebäude im Video erscheint(Wird mit den Sekunden verbunden)', verbose_name='Minuten'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timestamp',
            name='seconds',
            field=models.PositiveIntegerField(default=1, help_text='Geben sie hier die Sekunden an, an dem dasGebäude im Video erscheint(Wird mit den Minuten verbunden', validators=[django.core.validators.MaxValueValidator(60, 'Sekunden können nur zwischen 0 und 60 angegeben werden')], verbose_name='Sekunden'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='building',
            field=models.ForeignKey(help_text='Zugehöriges Gebäude', null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.building', verbose_name='Gebäude'),
        ),
        migrations.AlterField(
            model_name='timestamp',
            name='video',
            field=models.ForeignKey(help_text='Zugehöriges Video', on_delete=django.db.models.deletion.CASCADE, to='video_content.video', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='era',
            field=models.ForeignKey(help_text='Epoche des Videos auswählen.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details_page.era', verbose_name='1. Epoche'),
        ),
        migrations.AlterField(
            model_name='video',
            name='era2',
            field=models.ForeignKey(blank=True, help_text='Falls das Video in zwei Epochen fällt,\n                             kann hier eine zweite\n                             hinzugefügt werden. Diese Feld kann auch leer bleiben.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='details_page.era', verbose_name='2. Epoche'),
        ),
        migrations.AlterField(
            model_name='video',
            name='intro',
            field=models.BooleanField(default=False, help_text='Ist dieses Video das Intro-Video?', verbose_name='Einführung'),
        ),
        migrations.AlterField(
            model_name='video',
            name='length',
            field=models.FloatField(default=0.0, help_text='Länge des Videos', validators=[django.core.validators.MinValueValidator(0.0, 'Keine Werte kleiner als Null')], verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='Titel des Videos', max_length=100, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Videodatei in .mp4', upload_to='videos/', verbose_name='Video'),
        ),
    ]
