# Generated by Django 3.1.5 on 2021-03-03 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_content', '0006_remove_video_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='seconds',
            field=models.PositiveIntegerField(help_text='Geben sie hier die Sekunden an, an dem dasGebäude im Video erscheint(Wird mit den Minuten verbunden', validators=[django.core.validators.MaxValueValidator(59, 'Sekunden können nur zwischen 0 und 60 (exklusiv) angegeben werden')], verbose_name='Sekunden'),
        ),
    ]
