# Generated by Django 3.1.5 on 2021-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20211104_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.CharField(help_text='Inhalt der Ankündigung (max. 105 Zeichen).', max_length=105, verbose_name='Inhalt'),
        ),
    ]
