# Generated by Django 3.1.14 on 2022-02-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20211109_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(choices=[('Wartungsarbeiten', 'Wartungsarbeiten'), ('Jetzt Neu', 'Jetzt Neu'), ('Neues Vorlesungsvideo', 'Neues Vorlesungsvideo'), ('Klausur', 'Klausur'), ('Erinnerung', 'Erinnerung')], help_text='Den Typ der Ankündigung auswählen.', max_length=30, verbose_name='Titel'),
        ),
    ]
