# Generated by Django 3.1.14 on 2022-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_auto_20220211_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktiv?'),
        ),
    ]
