# Generated by Django 3.1.5 on 2021-02-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung zur Wiedererkennung', max_length=100, verbose_name='Bezeichnung')),
                ('course_link', models.CharField(help_text='Link zum Vorlesungskurs inMoodle', max_length=1000, verbose_name='Kurslink')),
            ],
            options={
                'verbose_name': 'Impressum',
                'verbose_name_plural': 'Impressen',
            },
        ),
    ]
