# Generated by Django 3.1.5 on 2021-01-15 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Titel des Bauplans eingeben (max. 100 Zeichen).', max_length=100)),
                ('description', models.TextField(help_text='Beschreibung des Bauplans eingeben (max. 1000 Zeichen).', max_length=1000)),
                ('blueprint', models.FileField(help_text='Auf "Durchsuchen" drücken um einen Bauplan hochzuladen.', upload_to='blueprints/')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.building')),
            ],
        ),
    ]
