# Generated by Django 3.1.5 on 2021-01-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='usable_as_thumbnail',
            field=models.BooleanField(default=False, help_text='Anwählen wenn das Bild als Thumbnail (Vorschaubild) für sein \n                                              Bauwerk in der Zeitachse und den Bauwerken erscheinen darf. Bei mehreren \n                                              möglichen Vorschaubildern für ein Bauwerk wird zufällig eins '),
        ),
    ]
