# Generated by Django 3.1.5 on 2021-01-29 16:34

import details_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0002_auto_20210126_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='area',
            field=models.FloatField(blank=True, help_text='Fläche des Bauwerks eingeben (falls vorhanden, in ha).', null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='construction',
            field=models.CharField(blank=True, help_text='Konstruktion des Bauwerks eingeben \n                                    (z.B. Massivbau, etc., falls vorhanden, max. 100 Zeichen)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='context',
            field=models.CharField(blank=True, help_text='Kontext des Bauwerks eingeben (Haus, Siedlung, \n                               öfftl. Platz etc., "max. 100 Zeichen)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='era',
            name='color_code',
            field=models.CharField(default='ffffff', help_text="Hier 6. stelligen Hex-Farbcode für die\n                                  Epoche eingeben (ohne das führende '#')(z.B.: #ffffff = Weiß).", max_length=6, validators=[details_page.models.validate_color_code]),
        ),
        migrations.AlterField(
            model_name='era',
            name='visible_on_video_page',
            field=models.BooleanField(default=True, help_text="Angeben ob die Epoche\n                                                auf der 'Staffeln' Seite sichtbar sein soll."),
        ),
        migrations.AlterField(
            model_name='picture',
            name='usable_as_thumbnail',
            field=models.BooleanField(default=False, help_text='Anwählen wenn das Bild als Thumbnail \n                                              (Vorschaubild) für sein Bauwerk in der Zeitachse,\n                                              der Bauwerke-Seite, und in den Suchergebnissen \n                                              erscheinen darf. \n                                              Bei mehreren möglichen Vorschaubildern für ein Bauwerk \n                                              wird zufällig eins ausgewählt.'),
        ),
    ]
