# Generated by Django 3.1.5 on 2021-01-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0002_auto_20210119_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='height',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='width',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='blueprint',
            field=models.ImageField(height_field='height', help_text='Auf "Durchsuchen" drücken um einen Bauplan hochzuladen.', upload_to='blueprint/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung des Bildes eingeben (max. 1000 Zeichen).', max_length=1000, null=True),
        ),
    ]
