# Generated by Django 3.1.5 on 2021-01-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0003_auto_20210119_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung des Gebäudes angeben (max. 1000 Zeichen', max_length=1000, null=True),
        ),
    ]
