# Generated by Django 3.1.5 on 2021-02-16 13:33

import details_page.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0004_auto_20210203_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={'verbose_name': 'Bauplan', 'verbose_name_plural': 'Baupläne'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Gebäude', 'verbose_name_plural': 'Gebäude'},
        ),
        migrations.AlterModelOptions(
            name='era',
            options={'verbose_name': 'Epoche', 'verbose_name_plural': 'Epochen'},
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='blueprint',
            field=models.ImageField(height_field='height', help_text='Auf "Durchsuchen" drücken um einen Bauplan hochzuladen.', upload_to='blueprint/', verbose_name='Bauplan', width_field='width'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.building', verbose_name='Gebäude'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung des Bildes eingeben (max. 1000 Zeichen).', max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='name',
            field=models.CharField(help_text='Titel des Bauplans eingeben (max. 100 Zeichen).', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='architect',
            field=models.CharField(blank=True, help_text='Architekt des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Architekt'),
        ),
        migrations.AlterField(
            model_name='building',
            name='area',
            field=models.FloatField(blank=True, help_text='Fläche des Bauwerks eingeben (falls vorhanden, in ha).', null=True, verbose_name='Fläche'),
        ),
        migrations.AlterField(
            model_name='building',
            name='builder',
            field=models.CharField(blank=True, help_text='Bauherren des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Bauherr'),
        ),
        migrations.AlterField(
            model_name='building',
            name='circumference',
            field=models.FloatField(blank=True, help_text='Durchmesser des Bauwerks eingeben (falls vorhanden).', null=True, verbose_name='Durchmesser'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(blank=True, help_text='Stadt des Bauweks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Stadt'),
        ),
        migrations.AlterField(
            model_name='building',
            name='column_order',
            field=models.CharField(blank=True, help_text='Säulenordnung des Gebäudes eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Säulenordnung'),
        ),
        migrations.AlterField(
            model_name='building',
            name='construction',
            field=models.CharField(blank=True, help_text='Konstruktion des Bauwerks eingeben(z.B. Massivbau, etc., falls vorhanden, max. 100 Zeichen)', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Konstruktion'),
        ),
        migrations.AlterField(
            model_name='building',
            name='construction_type',
            field=models.CharField(blank=True, help_text='Bautyp des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Bautyp'),
        ),
        migrations.AlterField(
            model_name='building',
            name='context',
            field=models.CharField(blank=True, help_text='Kontext des Bauwerks eingeben (Haus, Siedlung, öfftl. Platz etc., max. 100 Zeichen)', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Kontext'),
        ),
        migrations.AlterField(
            model_name='building',
            name='country',
            field=models.CharField(blank=True, choices=[('Afghanistan', 'AF - Afghanistan'), ('Åland', 'AX - Åland'), ('Albanien', 'AL - Albanien'), ('Algerien', 'DZ - Algerien'), ('Amerikanisch-Samoa', 'AS - Amerikanisch-Samoa'), ('Andorra', 'AD - Andorra'), ('Angola', 'AO - Angola'), ('Anguilla', 'AI - Anguilla'), ('Antarktis', 'AQ - Antarktis'), ('Antigua und Barbuda', 'AG - Antigua und Barbuda'), ('Argentinien', 'AR - Argentinien'), ('Armenien', 'AM - Armenien'), ('Aruba', 'AW - Aruba'), ('Australien', 'AU - Australien'), ('Österreich', 'AT - Österreich'), ('Aserbaidschan', 'AZ - Aserbaidschan'), ('Bahamas', 'BS - Bahamas'), ('Bahrain', 'BH - Bahrain'), ('Bangladesch', 'BD - Bangladesch'), ('Barbados', 'BB - Barbados'), ('Weißrussland', 'BY - Weißrussland'), ('Belgien', 'BE - Belgien'), ('Belize', 'BZ - Belize'), ('Benin', 'BJ - Benin'), ('Bermuda', 'BM - Bermuda'), ('Bhutan', 'BT - Bhutan'), ('Bolivien', 'BO - Bolivien'), ('Bonaire, Sint Eustatius und Saba', 'BQ - Bonaire, Sint Eustatius und Saba'), ('Bosnien und Herzegowina', 'BA - Bosnien und Herzegowina'), ('Botswana', 'BW - Botswana'), ('Bouvetinsel', 'BV - Bouvetinsel'), ('Brasilien', 'BR - Brasilien'), ('Britisches Territorium im Indischen Ozean', 'IO - Britisches Territorium im Indischen Ozean'), ('Britische Jungferninseln', 'VG - Britische Jungferninseln'), ('Brunei', 'BN - Brunei'), ('Bulgarien', 'BG - Bulgarien'), ('Burkina Faso', 'BF - Burkina Faso'), ('Burundi', 'BI - Burundi'), ('Kambodscha', 'KH - Kambodscha'), ('Kamerun', 'CM - Kamerun'), ('Kanada', 'CA - Kanada'), ('Kap Verde', 'CV - Kap Verde'), ('Kaimaninseln', 'KY - Kaimaninseln'), ('Zentralafrikanische Republik', 'CF - Zentralafrikanische Republik'), ('Tschad', 'TD - Tschad'), ('Chile', 'CL - Chile'), ('China', 'CN - China'), ('Weihnachtsinsel', 'CX - Weihnachtsinsel'), ('Kokosinseln', 'CC - Kokosinseln'), ('Kolumbien', 'CO - Kolumbien'), ('Komoren', 'KM - Komoren'), ('Cookinseln', 'CK - Cookinseln'), ('Costa Rica', 'CR - Costa Rica'), ('Kroatien', 'HR - Kroatien'), ('Kuba', 'CU - Kuba'), ('Curacao', 'CW - Curacao'), ('Zypern', 'CY - Zypern'), ('Tschechische Republik', 'CZ - Tschechische Republik'), ('Demokratische Republik Kongo', 'CD - Demokratische Republik Kongo'), ('Dänemark', 'DK - Dänemark'), ('Dschibuti', 'DJ - Dschibuti'), ('Dominica', 'DM - Dominica'), ('Dominikanische Republik', 'DO - Dominikanische Republik'), ('Osttimor', 'TL - Osttimor'), ('Ecuador', 'EC - Ecuador'), ('Ägypten', 'EG - Ägypten'), ('El Salvador', 'SV - El Salvador'), ('Äquatorialguinea', 'GQ - Äquatorialguinea'), ('Eritrea', 'ER - Eritrea'), ('Estland', 'EE - Estland'), ('Äthiopien', 'ET - Äthiopien'), ('Falkland-Inseln', 'FK - Falkland-Inseln'), ('Färöer-Inseln', 'FO - Färöer-Inseln'), ('Fidschi', 'FJ - Fidschi'), ('Finnland', 'FI - Finnland'), ('Frankreich', 'FR - Frankreich'), ('Französisch-Guayana', 'GF - Französisch-Guayana'), ('Französisch-Polynesien', 'PF - Französisch-Polynesien'), ('Französische Süd- und Antarktisgebiete', 'TF - Französische Süd- und Antarktisgebiete'), ('Gabun', 'GA - Gabun'), ('Gambia', 'GM - Gambia'), ('Georgien', 'GE - Georgien'), ('Deutschland', 'DE - Deutschland'), ('Ghana', 'GH - Ghana'), ('Gibraltar', 'GI - Gibraltar'), ('Griechenland', 'GR - Griechenland'), ('Grönland', 'GL - Grönland'), ('Grenada', 'GD - Grenada'), ('Guadeloupe', 'GP - Guadeloupe'), ('Guam', 'GU - Guam'), ('Guatemala', 'GT - Guatemala'), ('Guernsey', 'GG - Guernsey'), ('Guinea', 'GN - Guinea'), ('Guinea-Bissau', 'GW - Guinea-Bissau'), ('Guyana', 'GY - Guyana'), ('Haiti', 'HT - Haiti'), ('Heard und McDonaldinseln', 'HM - Heard und McDonaldinseln'), ('Honduras', 'HN - Honduras'), ('Hongkong', 'HK - Hongkong'), ('Ungarn', 'HU - Ungarn'), ('Island', 'IS - Island'), ('Indien', 'IN - Indien'), ('Indonesien', 'ID - Indonesien'), ('Iran', 'IR - Iran'), ('Irak', 'IQ - Irak'), ('Irland', 'IE - Irland'), ('Isle of Man', 'IM - Isle of Man'), ('Israel', 'IL - Israel'), ('Italien', 'IT - Italien'), ('Elfenbeinküste', 'CI - Elfenbeinküste'), ('Jamaika', 'JM - Jamaika'), ('Japan', 'JP - Japan'), ('Jersey', 'JE - Jersey'), ('Jordanien', 'JO - Jordanien'), ('Kasachstan', 'KZ - Kasachstan'), ('Kenia', 'KE - Kenia'), ('Kiribati', 'KI - Kiribati'), ('Kosovo', 'XK - Kosovo'), ('Kuwait', 'KW - Kuwait'), ('Kirgisistan', 'KG - Kirgisistan'), ('Laos', 'LA - Laos'), ('Lettland', 'LV - Lettland'), ('Libanon', 'LB - Libanon'), ('Lesotho', 'LS - Lesotho'), ('Liberia', 'LR - Liberia'), ('Libyen', 'LY - Libyen'), ('Liechtenstein', 'LI - Liechtenstein'), ('Litauen', 'LT - Litauen'), ('Luxemburg', 'LU - Luxemburg'), ('Macao', 'MO - Macao'), ('Mazedonien', 'MK - Mazedonien'), ('Madagaskar', 'MG - Madagaskar'), ('Malawi', 'MW - Malawi'), ('Malaysia', 'MY - Malaysia'), ('Malediven', 'MV - Malediven'), ('Mali', 'ML - Mali'), ('Malta', 'MT - Malta'), ('Marshallinseln', 'MH - Marshallinseln'), ('Martinique', 'MQ - Martinique'), ('Mauretanien', 'MR - Mauretanien'), ('Mauritius', 'MU - Mauritius'), ('Mayotte', 'YT - Mayotte'), ('Mexiko', 'MX - Mexiko'), ('Mikronesien', 'FM - Mikronesien'), ('Moldawien', 'MD - Moldawien'), ('Monaco', 'MC - Monaco'), ('Mongolei', 'MN - Mongolei'), ('Montenegro', 'ME - Montenegro'), ('Montserrat', 'MS - Montserrat'), ('Marokko', 'MA - Marokko'), ('Mosambik', 'MZ - Mosambik'), ('Myanmar', 'MM - Myanmar'), ('Namibia', 'NA - Namibia'), ('Nauru', 'NR - Nauru'), ('Nepal', 'NP - Nepal'), ('Niederlande', 'NL - Niederlande'), ('Niederländische Antillen', 'AN - Niederländische Antillen'), ('Neukaledonien', 'NC - Neukaledonien'), ('Neuseeland', 'NZ - Neuseeland'), ('Nicaragua', 'NI - Nicaragua'), ('Niger', 'NE - Niger'), ('Nigeria', 'NG - Nigeria'), ('Niue', 'NU - Niue'), ('Norfolkinsel', 'NF - Norfolkinsel'), ('Nordkorea', 'KP - Nordkorea'), ('Nördliche Marianen', 'MP - Nördliche Marianen'), ('Norwegen', 'NO - Norwegen'), ('Oman', 'OM - Oman'), ('Pakistan', 'PK - Pakistan'), ('Palau', 'PW - Palau'), ('Palästinensische Autonomiegebiete', 'PS - Palästinensische Autonomiegebiete'), ('Panama', 'PA - Panama'), ('Papua-Neuguinea', 'PG - Papua-Neuguinea'), ('Paraguay', 'PY - Paraguay'), ('Peru', 'PE - Peru'), ('Philippinen', 'PH - Philippinen'), ('Pitcairninseln', 'PN - Pitcairninseln'), ('Polen', 'PL - Polen'), ('Portugal', 'PT - Portugal'), ('Puerto Rico', 'PR - Puerto Rico'), ('Katar', 'QA - Katar'), ('Republik Kongo', 'CG - Republik Kongo'), ('Réunion', 'RE - Réunion'), ('Rumänien', 'RO - Rumänien'), ('Russland', 'RU - Russland'), ('Ruanda', 'RW - Ruanda'), ('Saint-Barthélemy', 'BL - Saint-Barthélemy'), ('St. Helena', 'SH - St. Helena'), ('St. Kitts und Nevis', 'KN - St. Kitts und Nevis'), ('St. Lucia', 'LC - St. Lucia'), ('St. Martin', 'MF - St. Martin'), ('Saint-Pierre und Miquelon', 'PM - Saint-Pierre und Miquelon'), ('St. Vincent und die Grenadinen', 'VC - St. Vincent und die Grenadinen'), ('Samoa', 'WS - Samoa'), ('San Marino', 'SM - San Marino'), ('São Tomé und Príncipe', 'ST - São Tomé und Príncipe'), ('Saudi-Arabien', 'SA - Saudi-Arabien'), ('Senegal', 'SN - Senegal'), ('Serbien', 'RS - Serbien'), ('Serbien und Montenegro', 'CS - Serbien und Montenegro'), ('Seychellen', 'SC - Seychellen'), ('Sierra Leone', 'SL - Sierra Leone'), ('Singapur', 'SG - Singapur'), ('Sint Maarten', 'SX - Sint Maarten'), ('Slowakei', 'SK - Slowakei'), ('Slowenien', 'SI - Slowenien'), ('Salomon-Inseln', 'SB - Salomon-Inseln'), ('Somalia', 'SO - Somalia'), ('Südafrika', 'ZA - Südafrika'), ('Südgeorgien und die Südlichen Sandwichinseln', 'GS - Südgeorgien und die Südlichen Sandwichinseln'), ('Südkorea', 'KR - Südkorea'), ('Südsudan', 'SS - Südsudan'), ('Spanien', 'ES - Spanien'), ('Sri Lanka', 'LK - Sri Lanka'), ('Sudan', 'SD - Sudan'), ('Suriname', 'SR - Suriname'), ('Svalbard und Jan Mayen', 'SJ - Svalbard und Jan Mayen'), ('Swasiland', 'SZ - Swasiland'), ('Schweden', 'SE - Schweden'), ('Schweiz', 'CH - Schweiz'), ('Syrien', 'SY - Syrien'), ('Taiwan', 'TW - Taiwan'), ('Tadschikistan', 'TJ - Tadschikistan'), ('Tansania', 'TZ - Tansania'), ('Thailand', 'TH - Thailand'), ('Togo', 'TG - Togo'), ('Tokelau', 'TK - Tokelau'), ('Tonga', 'TO - Tonga'), ('Trinidad und Tobago', 'TT - Trinidad und Tobago'), ('Tunesien', 'TN - Tunesien'), ('Türkei', 'TR - Türkei'), ('Turkmenistan', 'TM - Turkmenistan'), ('Turks- und Caicosinseln', 'TC - Turks- und Caicosinseln'), ('Tuvalu', 'TV - Tuvalu'), ('Amerikanische Jungferninseln', 'VI - Amerikanische Jungferninseln'), ('Uganda', 'UG - Uganda'), ('Ukraine', 'UA - Ukraine'), ('Vereinte Arabische Emirate', 'AE - Vereinte Arabische Emirate'), ('Großbritannien', 'GB - Großbritannien'), ('Vereinigte Staaten von Amerika (USA)', 'US - Vereinigte Staaten von Amerika (USA)'), ('United States Minor Outlying Islands', 'UM - United States Minor Outlying Islands'), ('Uruguay', 'UY - Uruguay'), ('Usbekistan', 'UZ - Usbekistan'), ('Vanuatu', 'VU - Vanuatu'), ('Vatikanstadt', 'VA - Vatikanstadt'), ('Venezuela', 'VE - Venezuela'), ('Vietnam', 'VN - Vietnam'), ('Wallis und Futuna', 'WF - Wallis und Futuna'), ('Westsahara', 'EH - Westsahara'), ('Jemen', 'YE - Jemen'), ('Sambia', 'ZM - Sambia'), ('Simbabwe', 'ZW - Simbabwe')], default='Griechenland', help_text='Hier Land des Bauwerks auswählen (Tipp:Zum Suchen Kürzelauf der Tastatur eingeben).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='building',
            name='date_ca',
            field=models.BooleanField(default=False, help_text='ca. zum Datum hinzufügen (für ungenaue Datumsangaben).', verbose_name='ungefähre Datumsangabe?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='date_century',
            field=models.BooleanField(default=False, help_text='Sind die Daten Jahrhundert Angaben?', verbose_name='Jahrhundertangaben?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='date_from',
            field=models.PositiveIntegerField(blank=True, help_text='Jahr des Baubeginns eingeben. Wenn nicht gesetzt, erscheint das Gebäude nicht auf der Zeitachse.', null=True, verbose_name='Baubeginn'),
        ),
        migrations.AlterField(
            model_name='building',
            name='date_from_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Baubeginns: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Baubeginn v.Chr./n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='date_to',
            field=models.PositiveIntegerField(blank=True, help_text='Jahr des Bauendes eingeben.', null=True, verbose_name='Bauende'),
        ),
        migrations.AlterField(
            model_name='building',
            name='date_to_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Bauendes: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Bauende v.Chr/n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text='Beschreibung des Gebäudes angeben (max. 1000 Zeichen', max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='building',
            name='design',
            field=models.CharField(blank=True, help_text='Bauform des Bauwerks angeben. (max. 100 Zeichen)', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Bauform'),
        ),
        migrations.AlterField(
            model_name='building',
            name='era',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.era', verbose_name='Epoche'),
        ),
        migrations.AlterField(
            model_name='building',
            name='function',
            field=models.CharField(blank=True, help_text='Gattung/Funktion des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Funktion'),
        ),
        migrations.AlterField(
            model_name='building',
            name='height',
            field=models.FloatField(blank=True, help_text='Höhe des Bauwerks eingeben (falls vorhanden, in m).', null=True, verbose_name='Höhe'),
        ),
        migrations.AlterField(
            model_name='building',
            name='length',
            field=models.FloatField(blank=True, help_text='Länge des Bauwerks eingeben (falls vorhanden, in m).', null=True, verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='building',
            name='literature',
            field=models.TextField(blank=True, help_text='Literatur zum Gebäude angeben (max. 1000 Zeichen).', max_length=1000, null=True, verbose_name='Literatur'),
        ),
        migrations.AlterField(
            model_name='building',
            name='material',
            field=models.CharField(blank=True, help_text='Material des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(help_text='Namen des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, validators=[details_page.models.validate_url_conform_str], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='region',
            field=models.CharField(blank=True, help_text='Region des Bauwerks eingeben (max. 100 Zeichen).', max_length=100, null=True, validators=[details_page.models.validate_url_conform_str], verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='building',
            name='width',
            field=models.FloatField(blank=True, help_text='Breite des Bauwerks eingeben (falls vorhanden, in m).', null=True, verbose_name='Breite'),
        ),
        migrations.AlterField(
            model_name='era',
            name='color_code',
            field=models.CharField(default='ffffff', help_text="Hier 6. stelligen Hex-Farbcode für die\n                                  Epoche eingeben (ohne das führende '#')(z.B.: #ffffff = Weiß).", max_length=6, validators=[details_page.models.validate_color_code], verbose_name='Farbkodierung'),
        ),
        migrations.AlterField(
            model_name='era',
            name='name',
            field=models.CharField(choices=[('Bronzezeit', 'Bronzezeit'), ('Frühzeit', 'Frühzeit'), ('Archaik', 'Archaik'), ('Klassik', 'Klassik'), ('Hellenismus', 'Hellenismus'), ('Königszeit', 'Königszeit'), ('Republik', 'Republik'), ('Frühe Kaiserzeit', 'Frühe Kaiserzeit'), ('Mittlere Kaiserzeit', 'Mittlere Kaiserzeit'), ('Späte Kaiserzeit', 'Späte Kaiserzeit'), ('Spätantike', 'Spätantike'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', help_text='Epoche auswählen.', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='era',
            name='visible_on_video_page',
            field=models.BooleanField(default=True, help_text="Angeben ob die Epoche\n                                                auf der 'Staffeln' Seite sichtbar sein soll.", verbose_name='Sichtbar auf Staffelseite?'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year_from',
            field=models.PositiveIntegerField(blank=True, help_text='Jahr des Beginns der Epoche eingeben.', null=True, verbose_name='Anfangsdatum'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year_from_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Beginns: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Anfangsdatum v.Chr./n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year_to',
            field=models.PositiveIntegerField(blank=True, help_text='Jahr des Endes der Epoche eingeben.', null=True, verbose_name='Enddatum'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year_to_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Endes: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Endatum v.Chr/n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='details_page.building', verbose_name='Gebäude'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung des Bildes eingeben (max. 1000 Zeichen).', max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(help_text='Titel des Bildes eingeben (max. 100 Zeichen).', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(height_field='height', help_text='Auf "Durchsuchen" drücken um ein Bild hochzuladen.', upload_to='pics/', verbose_name='Bild', width_field='width'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='usable_as_thumbnail',
            field=models.BooleanField(default=False, help_text='Anwählen wenn das Bild als Thumbnail (Vorschaubild) für sein Bauwerk in der Zeitachse, der Bauwerke-Seite, und in den Suchergebnissen erscheinen darf. Bei mehreren möglichen Vorschaubildern für ein Bauwerk wird zufällig eins ausgewählt.', verbose_name='Thumbnail?'),
        ),
    ]
