# Generated by Django 3.1.5 on 2021-02-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0005_auto_20210216_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text='Beschreibung des Bildes eingeben (max. 1000 Zeichen).', max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, editable=False, help_text='Beschreibung des Bildes eingeben (max. 1000 Zeichen).', max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
    ]
