# Generated by Django 3.1.5 on 2021-02-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0006_auto_20210216_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='era',
            name='name',
            field=models.CharField(choices=[('Bronzezeit', 'Bronzezeit'), ('Frühzeit', 'Frühzeit'), ('Archaik', 'Archaik'), ('Klassik', 'Klassik'), ('Hellenismus', 'Hellenismus'), ('Königszeit', 'Königszeit'), ('Republik', 'Republik'), ('Frühe Kaiserzeit', 'Frühe Kaiserzeit'), ('Mittlere Kaiserzeit', 'Mittlere Kaiserzeit'), ('Späte Kaiserzeit', 'Späte Kaiserzeit'), ('Spätantike', 'Spätantike'), ('Sonstiges', 'Sonstiges')], default='Sonstiges', help_text='Epoche auswählen.', max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
