# Generated by Django 3.1.5 on 2021-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0008_building_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='links',
            field=models.TextField(blank=True, default='', help_text='Weiterführende Links zum Gebäude angeben (max. 1000 Zeichen).', max_length=1000, null=True, verbose_name='Links'),
        ),
    ]
