# Generated by Django 3.1.5 on 2021-03-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0010_auto_20210303_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='links',
            field=models.TextField(blank=True, default='', help_text='Weiterführende Links zum Gebäude angeben (max. 1000 Zeichen).Es werden nur Links im folgenden Format erkannt:https://moodle.tu-darmstadt.de/my/', max_length=1000, null=True, verbose_name='Links'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_from_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='n.Chr.', help_text='Jahr des Baubeginns: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Baubeginn v.Chr./n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_to_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='n.Chr.', help_text='Jahr des Bauendes: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Bauende v.Chr/n.Chr.?'),
        ),
    ]
