# Generated by Django 3.1.5 on 2021-03-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0012_auto_20210307_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, help_text='Beschreibung des Gebäudes angeben (max. 1000 Zeichen', max_length=1000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_from_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Baubeginns: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Baubeginn v.Chr./n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='building',
            name='year_to_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Bauendes: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Bauende v.Chr/n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='era',
            name='name',
            field=models.CharField(choices=[('Bronzezeit', 'Bronzezeit'), ('Frühe Eisenzeit', 'Frühe Eisenzeit'), ('Archaik', 'Archaik'), ('Klassik', 'Klassik'), ('Hellenismus', 'Hellenismus'), ('Kaiserzeit', 'Kaiserzeit'), ('Spätantike', 'Spätantike'), ('Rezeption', 'Rezeption')], help_text='Epoche auswählen.', max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year_from_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Beginns: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Anfangsdatum v.Chr./n.Chr.?'),
        ),
        migrations.AlterField(
            model_name='era',
            name='year_to_BC_or_AD',
            field=models.CharField(blank=True, choices=[('v.Chr.', 'v.Chr.'), ('n.Chr.', 'n.Chr.')], default='v.Chr.', help_text='Jahr des Endes: v.Chr. bzw. n.Chr. auswählen.', max_length=7, null=True, verbose_name='Enddatum v.Chr/n.Chr.?'),
        ),
    ]
