# Generated by Django 3.1.5 on 2021-11-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0013_auto_20210309_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='era',
            name='year_from_ca',
            field=models.BooleanField(default=False, verbose_name='Anfangsdatum ca.?'),
        ),
        migrations.AddField(
            model_name='era',
            name='year_to_ca',
            field=models.BooleanField(default=False, verbose_name='Enddatum ca.?'),
        ),
    ]
