# Generated by Django 3.1.14 on 2022-04-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_page', '0015_auto_20211210_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='year_ca',
            field=models.BooleanField(default=False, editable=False, help_text='ca. zum Datum hinzufügen (für ungenaue Datumsangaben).', verbose_name='ungefähre Jahresangabe?'),
        ),
    ]
